package Frames;

import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Kenth Alexis Osila
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        rescaleImages();
        // Set the frame icon
        ImageIcon img = new ImageIcon("C:\\Users\\aisa\\Documents\\NetBeansProjects\\Mathema-TicTacToe\\src\\Images\\gameLogo.png");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBg = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        lblBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MATHEMA-TICTACTOE");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBg.setMaximumSize(new java.awt.Dimension(1366, 768));
        panelBg.setMinimumSize(new java.awt.Dimension(1366, 768));
        panelBg.setPreferredSize(new java.awt.Dimension(1366, 768));
        panelBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgTitle.png"))); // NOI18N
        panelBg.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 1271, 113));

        btnPlay.setFont(new java.awt.Font("Imprint MT Shadow", 0, 48)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Play.png"))); // NOI18N
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        btnPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlay.setMaximumSize(new java.awt.Dimension(437, 113));
        btnPlay.setMinimumSize(new java.awt.Dimension(437, 113));
        btnPlay.setNextFocusableComponent(btnPlay);
        btnPlay.setPreferredSize(new java.awt.Dimension(437, 113));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        btnPlay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPlayKeyPressed(evt);
            }
        });
        panelBg.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 437, 113));

        lblBg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg1.png"))); // NOI18N
        panelBg.add(lblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        getContentPane().add(panelBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method rescale all the images that have been used in the frame
     */
    public void rescaleImages() {
        // Rescale background image
        Icon iBg = lblBg.getIcon();
        ImageIcon imgBg = (ImageIcon) iBg;
        Image imageBg = imgBg.getImage().getScaledInstance(lblBg.getWidth(), lblBg.getHeight(), Image.SCALE_SMOOTH);
        lblBg.setIcon(new ImageIcon(imageBg));

        // Rescale game title image
        Icon i = lblTitle.getIcon();
        ImageIcon imgIcon = (ImageIcon) i;
        Image image = imgIcon.getImage().getScaledInstance(lblTitle.getWidth(), lblTitle.getHeight(), Image.SCALE_SMOOTH);
        lblTitle.setIcon(new ImageIcon(image));

        // Rescale play button
        Icon iBtnPlay = btnPlay.getIcon();
        ImageIcon imgBtnPlay = (ImageIcon) iBtnPlay;
        Image imageBtnPlay = imgBtnPlay.getImage().getScaledInstance(btnPlay.getWidth(), btnPlay.getHeight(), Image.SCALE_SMOOTH);
        btnPlay.setIcon(new ImageIcon(imageBtnPlay));
    }

    /**
     * This button will make the program proceed to the next frame (SetNameJFrame) when play button clicked
     * @param evt - action event
     */
    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        SetNameJFrame setNameJFrame = new SetNameJFrame();
        setNameJFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPlayActionPerformed

    /**
     * This button will make the program proceed to the next frame (SetNameJFrame) when enter key is pressed
     * @param evt - action event
     */
    private void btnPlayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPlayKeyPressed
        // This conditio will check if the players pressed the enter key
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SetNameJFrame setNameJFrame = new SetNameJFrame();
            setNameJFrame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnPlayKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel lblBg;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelBg;
    // End of variables declaration//GEN-END:variables
}
